fix: use getManagers() as of Symfony 2.1
steevanb/doctrine-stats pull request #6
Opened 2017-08-30 12:39 UTC by gsdevme

<img width="1082" alt="screen shot 2017-08-30 at 13 34 43" src="https://user-images.githubusercontent.com/319498/29872642-5d5fee00-8d88-11e7-966b-06410a1b7707.png">

This drops support for anything < Symfony 2.1, I assume that isn't a big deal given its not a supported Symfony release anyway.

I've added a composer rule to flag it anyway, so should be clear.

2017-08-30 12:54 UTC, steevanb commented
Hi, ans thanks for your PR !

Symfony < 2.1 is not supported, as you said :)
doctrine-stats should work without Symfony, this is for Doctrine. There is a bridge to show data in Symfony, but you can use it with another framework, or a personnal project who use Doctrine without a framework.
So, symfony dependency here is not allowed ;)

2017-08-30 18:15 UTC, gsdevme commented
Hmm, this package should perhaps suggest `symfony/doctrine-bridge` at least, given it has source code with `use Symfony\Bridge\Doctrine\RegistryInterface;` 

Maybe even worth adding it to the require-dev.. but I do take your point. I will remove it

2017-09-01 08:47 UTC, steevanb requested changes

2017-09-01 08:47 UTC, steevanb commented on composer.json
> +        "doctrine/orm": "^2.4.8",
This is invalid JSON, can you remove the last `,` and empty line ?

2017-09-01 08:47 UTC, steevanb commented on Bridge/DoctrineStatsBundle/DataCollector/DoctrineStatsCollector.php
> +        foreach ($this->doctrine->getManagers() as $entityManager) {
`getManagers()` return instances of `ObjectManager`, but i need an instanceof `EntityManagerInterface` to call `getUnitOfWork()`. So i can't call `getManagers()` here

2017-11-16 00:54 UTC, closed without merging